### PR TITLE
Handle SQL-Injection 

### PR DESCRIPTION
**Pull request by HosseinDinarvand**
I add bellow changes:
1)  write store procedure query to use in EF core.
2) parameterize query in dapper in ADO.net and Dapeer ORMs

### CODE REVIEW

**Comment by HosseinDinarvand** [comment]
I'm sorry to push my already commit's, please check the three last commit's.

**Review by VahidFarahmandian — CHANGES_REQUESTED** [review]
Please put the .gitignore file inside your own folder so iy only effects your files instead of thw whole repo. 
Also there is conflicts in your proposed changes and the files in repo. Please resolve them too, prior to resubmitting the changes

**Comment by HosseinDinarvand** [comment]
OK, I will applay this changes to git ignore file.

**Comment by VahidFarahmandian** [comment]
> OK, I will applay this changes to git ignore file.

Great. Also there is conflicts in your proposed changes and the files in repo. Please resolve them too, prior to resubmitting the changes

**Pull request closed without merging**
